baseURL: https://arturo-source.github.io/
languageCode: en-us
title: Arturo Source website
theme: hugo-PaperMod

enableInlineShortcodes: true
enableRobotsTXT: true
enableEmoji: true

defaultContentLanguage: en

outputs:
  home:
    - HTML
    - RSS
    - JSON # is necessary

languages:
  en:
    languageName: ":uk:"
    weight: 1
    menu:
      main:
        - name: Archive
          url: archive
          weight: 1
        - name: Search
          url: search/
          weight: 2
    params:
      languageAltTitle: English

  es:
    languageName: ":es:"
    weight: 2
    menu:
      main:
        - name: Archivo
          url: archivo
          weight: 1
        - name: Buscar
          url: buscar/
          weight: 2
    params:
      languageAltTitle: Español
      homeInfoParams:
        Title: ¡Bienvenido!
        Content: Soy Arturo, un ingeniero informático enamorado del Software. En este blog escribiré todas las ideas y aportaciones que se me ocurran sobre desarrollo, Linux, e informática en general.

params:
  homeInfoParams:
    Title: Welcome!
    Content: I'm Arturo, a computer engineer in love with Software. I'll post all the ideas and contributions that come to mind about development, Linux, and IT in general at this blog.
  socialIcons:
    - name: github
      url: "https://github.com/arturo-source"
    - name: youtube
      url: "https://www.youtube.com/@arturosource"
    - name: twitter
      url: "https://twitter.com/ArturoSource"
  
  UseHugoToc: true
  ShowToc: true
  TocOpen: false
  ShowCodeCopyButtons: true
  displayFullLangName: true
  ShowBreadCrumbs: true
  ShowShareButtons: true
  ShowReadingTime: true
  env: production
